# Generated by Django 3.0.6 on 2020-06-03 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 3, 14, 10, 13, 675603, tzinfo=utc), verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 6, 3, 14, 10, 33, 755792, tzinfo=utc), verbose_name='last login'),
            preserve_default=False,
        ),
    ]
