# Generated by Django 3.0.6 on 2020-06-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producturl', models.CharField(max_length=1000)),
                ('dprice', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('cprice', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
