# Generated by Django 3.0.6 on 2020-06-04 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200604_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time Added'),
            preserve_default=False,
        ),
    ]
